### ISSUE TITLE
Race Condition : Attack Condition tries to connect to Model before it has started

### ISSUE THREAD

**Issue by spMohanty** [bveliqi/adversarial-vision-challenge#4] opened 2018-07-03 00:53 UTC
Both Attack and Model container should patiently wait for a fixed period of time in the beginning before considering throwing any of the errors.

In case of the `interpolation_targeted_attack_baseline` and the `resnet80_baseline` I noticed that the attack container throws a MAX_RETRIES_EXCEEDED error much before the resnet80 model has even initialized.

**Comment by jonasrauber** [comment] 2018-07-03 07:28
The model container is passive anyway, so it's not throwing these errors. The attack container should indeed wait for the mode to start and @bveliqi already implemented it: https://github.com/bethgelab/adversarial-vision-challenge/blob/master/adversarial_vision_challenge/utils.py#L65
My guess is that we need much longer wait periods in this function to give the model time to start. @spMohanty, do you think two minutes is enough, or should we try for five minutes (if I counted correctly, currently it's up to 54 seconds)? I think we did specify limits on how a long a model is allowed to take for initialization, right?
@wielandbrendel do we / should we check model initialization in the test-scripts? of course, this is only a rough estimate and it might be different on other machines…
@bveliqi can you fix this?

**Comment by bveliqi** [comment] 2018-07-03 08:13
@spMohanty: I'm not able to reproduce this...

```
2018-07-03 09:57:38,559 Retrying for the 1. time
2018-07-03 09:57:41,573 Retrying for the 2. time
2018-07-03 09:57:47,587 Retrying for the 3. time
2018-07-03 09:57:56,602 Retried request for 3 times. Giving up.
2018-07-03 09:57:56,622 Retrying for the 1. time
2018-07-03 09:57:59,638 Retrying for the 2. time
2018-07-03 09:58:05,653 Retrying for the 3. time
2018-07-03 09:58:14,672 Retried request for 3 times. Giving up.
2018-07-03 09:58:14,681 Retrying for the 1. time
2018-07-03 09:58:17,696 Retrying for the 2. time
2018-07-03 09:58:23,708 Retrying for the 3. time
2018-07-03 09:58:32,851 Retried request for 3 times. Giving up.
2018-07-03 09:58:32,851 Can't reach model server: http://gpu8:8988.
```

AS @jonasrauber  already mentioned: as we can see from the above logs the attack tries to reach the model server with a retry backoff strategy (waiting 3,6 and secs between each request) and doing this three times before finally giving up (which leads to 54 secs in total).

In this case a `AVC.ATTACK.RETRIES_EXCEEDED_ERROR` event would be sent to the backend: https://github.com/bethgelab/adversarial-vision-challenge/blob/master/adversarial_vision_challenge/retry_helper.py#L25 which I think is ok?

---

Also the `_check_rate_limitation` is called within the `/predict` request context; https://github.com/bethgelab/adversarial-vision-challenge/blob/master/adversarial_vision_challenge/server.py#L102

So I don't see how the `TooManyRequests` should be thrown, before the server has even started, if this is what you're referring to.

**Comment by bveliqi** [comment] 2018-07-03 08:17
@wielandbrendel as far as I remember you initially said that the attack should wait up to 20secs in the beginning for a model to start... 
@spMohanty @wielandbrendel what would be a good value to set here?
I would have thought that 54secs should be more than enough.

**Comment by wielandbrendel** [comment] 2018-07-03 08:32
@bveliqi We currently state a maximum of 100s for startup time, but I'd be happy to reduce this to 50 seconds (should be more than enough).

As for waiting: shouldn't the model client in the attack container block until the model server is actually available? This would be much better than waiting a fixed amount of time (which would be a waste of resources).

**Comment by spMohanty** [comment] 2018-07-03 13:23
@jonasrauber @wielandbrendel @bveliqi : Yeah a _max_ warm-startup timeout of 100s should be good !

I will have a look at this again, regarding the possible errors from the model, I meant some of the errors that we discussed but havent implemented, like the model throwing an errorr about an attacker which does not do anything at all (in which case it will end up hogging the resources on the cluster for the whole timeout - a few hours, unless we actively kill it with a separate timeout; or maybe an attacker which takes say an hour for a single adversarial - and hence would never manage to register all adversarials within the timeout, but will anyway continue hogging onto the resources until the whole timeout).

**Comment by bveliqi** [comment] 2018-07-04 16:10
@spMohanty It turns out #7 was different form this one, since it was an issue within the test binaries.
Nontheless, I will close this issue for now since we have #9 for adding further notifications.

**Closed as completed by bveliqi** 2018-07-04 16:10 UTC

**Comment by spMohanty** [comment] 2018-07-05 15:01
@bveliqi  : Just realized something rather silly, it is wrong to assume both the model and attackers would be scheduled and started at exactly the same time !
Based on how k8 schedulers work, there can still be a difference in the time between the start of a model and the start of an attack.

Can we make the initial wait time configurable (as an env variable), so that in the grading infrastructure we can have the attack patiently wait a comfortable 5 minutes just to be safe.
